feat(*): Adds wadm examples for our most commonly used example actors
wasmCloud/examples pull request #155
Opened 2022-08-30 17:19 UTC by thomastaylor312

Note that this purposefully doesn't add full documentation to READMEs
because setting up wadm is an extra step right now. Once we add support
for it in `wash up` by default, we can add the instructions for running
in wadm. As an intermediate step, instructions were added as a comment
to the top of the wadm manifests

2022-08-30 17:19 UTC, thomastaylor312 commented
Please note that this is dependent on https://github.com/wasmCloud/wadm/pull/35 being merged and released

2022-08-30 18:42 UTC, brooksmtownsend requested changes
These look great!

2022-08-30 18:42 UTC, brooksmtownsend commented on petclinic/docker/docker-compose.yml
> +    image: wasmcloud.azurecr.io/wadm:0.2.2
Will need to upgrade to 0.3.0 or equivalent after the spreadscaler changes

2022-08-30 18:42 UTC, brooksmtownsend commented on petclinic/docker/docker-compose.yml
> +    image: wasmcloud.azurecr.io/wadm:0.2.2
(as you mentioned, just requesting changes to prevent the merge)

2022-09-01 17:55 UTC, brooksmtownsend approved these changes

2022-09-01 18:00 UTC, merged