HTTP-Fib example
wasmCloud/examples pull request #49
Opened 2021-05-13 15:44 UTC by brooksmtownsend

Uploading the example used in the last community meeting, including the VSCode tasks.json. This depends on #48 for inmemory-keyvalue to get published, so I'm leaving as a draft for now.

2021-05-20 14:06 UTC, autodidaddict requested changes
Just a suggestion to take the personal email address of the manifest

2021-05-20 14:06 UTC, autodidaddict commented on http-fib/Cargo.toml
> +authors = ["Brooks Townsend <brooksmtownsend@gmail.com>"]
might want to switch this to a team name.

2021-05-20 14:06 UTC, autodidaddict commented on http-fib/manifest.yaml
> +  - actor: ${FIB_ACTOR:MDVUB2IKGSH634XUWJSKJPSCLLLUCPOZL3HTYYCE6IC34A42UOHWTQ4P}
Can we put a comment at the top of the file explanining what FIB_ACTOR is and how they should use it?

2021-06-14 20:15 UTC, brooksmtownsend commented
@autodidaddict bumping this PR, addressed the personal email 👍🏻

2021-07-21 01:08 UTC, brooksmtownsend commented
@autodidaddict I won't be upset if we don't want to keep this example but it is ready and composed of actors (no providers to update for OTP runtime) just making sure you didn't close instead of merging on accident.

2021-07-21 10:34 UTC, autodidaddict commented
Didn't mean to close this. We can leave this open until it'd upgraded to the latest bits.

2021-08-07 13:43 UTC, autodidaddict approved these changes

2021-08-07 13:53 UTC, merged